#!/usr/bin/env bash

[[ "${TRACE}" ]] && set -x
set -eou pipefail
shopt -s nullglob

script="$(basename $0)"

main() {
	declare -A repos=([nix-cfg]=master [nix-config-old]=main [notes]=main [dotfiles]=master [dotfiles-old]=master [nix-flakebox]=main)
	git init

	git add bootstrap-repo
	git commit -m 'init setup commit'

	for r in "${!repos[@]}"; do
		branch="${repos[$r]}"
		git remote add "$r" "git@github.com:esselius/$r.git"
		git fetch "$r"

		git merge --allow-unrelated-histories --no-edit "$r/$branch"
		git rm -rf .
		git reset HEAD "$script"
		git add .
		git reset HEAD bootstrap-repo
		git commit -m "drop github.com/esselius/$r"
	done

	git remote add origin git@github.com:esselius/setup.git

	# manual git push
}

main "$@"