#!/usr/bin/env bash

[[ "${TRACE}" ]] && set -x
set -eou pipefail
shopt -s nullglob

main() {
  pushd ~ >/dev/null

  sops -e "$1" >"$1.enc"

  git --git-dir=$HOME/.cfg/ --work-tree=$HOME add "$1.enc"

  popd >/dev/null
}

main "$@"
