#!/usr/bin/env bash

[[ "${TRACE}" ]] && set -x
set -eou pipefail
shopt -s nullglob

main() {
  local file="${1:?Gimmie a file as first arg yo}"
  echo "Local IPs:"
  ifconfig|grep inet

  echo ""
  echo "Listening to port 1234!"

  nc -l 1234 < /dev/null | pv > "${file}"
}

main "$@"
