#!/usr/bin/env bash

[[ "${TRACE}" ]] && set -x
set -eou pipefail
shopt -s nullglob

main() {
  mkdir -p .github
  cat >.github/settings.yml <<EOF
_extends: .github
EOF

#  git add .github/settings.yml
#  git commit -m "Add probot-settings config"
}

main "$@"
