#!/usr/bin/env fish

# Automatically generated by Boxen. Don't edit directly. This file
# sets up paths and basic environment for the Boxen dev environment,
# and is intended to be sourced in your shell profile.

# set +e
# set +u

# Make the root of Boxen available.

set -x BOXEN_HOME /opt/boxen

# Add homebrew'd stuff to the path.

set -x PATH $BOXEN_HOME/homebrew/bin $BOXEN_HOME/homebrew/sbin $PATH

# Add homebrew'd stuff to the manpath.

set -x MANPATH $BOXEN_HOME/homebrew/share/man $MANPATH

# Add any binaries specific to Boxen to the path.

set -x PATH $BOXEN_HOME/bin $PATH

###### PARSE ERR: for f in $BOXEN_HOME/env.d/*.sh ; do
###### PARSE ERR:   if [ -f $f ] ; then
###### PARSE ERR:     source $f
###### PARSE ERR:   fi
###### PARSE ERR: done

# Add ./bin to the path. This happens after initialization to make
# sure local stubs take precedence over stuff like rbenv.

set -x PATH bin $PATH

# Boxen is active.

###### PARSE ERR: if [ -d "$BOXEN_HOME/repo/.git" ]; then
set -x BOXEN_SETUP_VERSION (env GIT_DIR=$BOXEN_HOME/repo/.git git rev-parse --short HEAD)
###### PARSE ERR: else
###### PARSE ERR:   echo "Boxen could not load properly!"
###### PARSE ERR: fi
set -x CFLAGS "-I$BOXEN_HOME/homebrew/include"
# Expose basic setup paths. BOXEN_HOME is already exported at the top level.

set -x BOXEN_BIN_DIR /opt/boxen/bin
set -x BOXEN_CONFIG_DIR /opt/boxen/config
set -x BOXEN_DATA_DIR /opt/boxen/data
set -x BOXEN_ENV_DIR /opt/boxen/env.d
set -x BOXEN_LOG_DIR /opt/boxen/log
set -x BOXEN_SOCKET_DIR /opt/boxen/data/project-sockets
set -x BOXEN_SRC_DIR /Users/pepp/src
# Expose GitHub credentials

set -x BOXEN_GITHUB_LOGIN pepps
set -x HOMEBREW_CACHE $BOXEN_HOME/cache/homebrew
# Make all the fancy `hub` shortcuts available via `git`.

###### PARSE ERR: eval "$(hub alias -s)"
set -x LDFLAGS "-L$BOXEN_HOME/homebrew/lib"
# Configure and activate nodenv. You know, for nodes.

set -x NODENV_ROOT $BOXEN_HOME/nodenv

set -x PATH $BOXEN_HOME/nodenv/bin $PATH

###### PARSE ERR: eval "$(nodenv init -)"

# Configure and activate rbenv. You know, for rubies.

set -x RBENV_ROOT $BOXEN_HOME/rbenv

set -x PATH $BOXEN_HOME/rbenv/bin $BOXEN_HOME/rbenv/plugins/ruby-build/bin $PATH

###### PARSE ERR: eval "$(rbenv init -)"
set -x PATH /opt/boxen/rbenv/shims /opt/boxen/rbenv/bin $PATH
rbenv rehash 2>/dev/null
function git ; hub $argv ; end
